name: Build PDF (xu-cheng)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 如果有额外系统依赖/字体，在这里装（可删掉）
      - name: Install extra packages (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      # 用 xu-cheng/latex-action 编译
      - name: LaTeX build (XeLaTeX + latexmk)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: dx-real-analysis.tex      # ← 主文件名（改成你的）
          latexmk_use_xelatex: true            # 使用 xelatex
          # 如果用 biber（参考文献），开启下一行
          # extra_system_packages: "biber"
          # latexmk_shell_escape: true         # 若需要 -shell-escape

      # 上传 PDF（和 root_file 同名）
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf-xu-cheng
          path: dx-real-analysis.pdf          # ← 与 root_file 同名的 .pdf这个复制进workflow里面以后生成的pdf叫什么啊
