name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-pdf:
    name: Compile LaTeX to PDF
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 TeX Live & Biber（含中日韩字体）
      - name: Install TeX Live and Biber
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-bibtex-extra \
            biber \
            fonts-noto-cjk

      # 3. 第一次编译
      - name: First XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 4. 参考文献
      - name: Run Biber
        run: biber dx-real-analysis || true

      # 5. 第二次编译
      - name: Second XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 6. 第三次编译
      - name: Final XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 6.5 构建后列出文件（仅命令，无中文）
      - name: List files after build
        run: |
          pwd
          ls -lah
          ls -lah *.pdf || true
          ls -lah **/*.pdf || true

      # 7. 上传 PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: dx-real-analysis-pdf
          path: dx-real-analysis.pdf
